### POST BAR
POST http://{{host}}:{{port}}/api/v1/bar
Content-Type: application/json

{
  "no" : "1",
  "lyrics" : "언제부턴가",
  "fingeringId" : "1",
  "sheetId" : "1"
}

### GET BAR
GET http://{{host}}:{{port}}/api/v1/bar/1

### GET BAR LIST
GET http://{{host}}:{{port}}/api/v1/bar?page=0&size=10

### EMPTY QUERY ALL BAR
POST http://{{host}}:{{port}}/api/v1/bar/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "",
      "values" : [""],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "and"
}

### QUERY ALL BAR
POST http://{{host}}:{{port}}/api/v1/bar/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "sheetId",
      "values" : ["2"],
      "queryOption" : "equal"
    }
  ],
  "conditionOption" : "or"
}

### PUT BAR
PUT http://{{host}}:{{port}}/api/v1/bar/6
Content-Type: application/json

{
  "no": "6",
  "lyrics": "룰 수 없",
  "fingeringId": "-4229780812172121644",
  "sheetId": "2"
}

### DELETE BAR
DELETE http://{{host}}:{{port}}/api/v1/bar/1