### POST FINGERING
POST http://{{host}}:{{port}}/api/v1/fingering
Content-Type: application/json

{
  "type" : "guitar",
  "chord" : "C",
  "notes" : [
    {
      "line" : "5",
      "space" : "2"
    },
    {
      "line" : "3",
      "space" : "7"
    }
  ]
}

### GET FINGERING
GET http://{{host}}:{{port}}/api/v1/fingering/-4229780812172121644

### GET FINGERING LIST
GET http://{{host}}:{{port}}/api/v1/fingering?page=0&size=10

### GET FINGERING LIST BY CHORD
GET http://{{host}}:{{port}}/api/v1/fingering/chord/Fm

### PUT FINGERING
PUT http://{{host}}:{{port}}/api/v1/fingering/-4229780812172121644
Content-Type: application/json

{
  "type" : "guitar",
  "chord" : "Fm",
  "notes" : [
    {
      "line" : "3",
      "space" : "6"
    },
    {
      "line" : "4",
      "space" : "6"
    }
  ]
}

### DELETE FINGERING
DELETE http://{{host}}:{{port}}/api/v1/fingering/1