### POST FINGERING
POST http://{{host}}:{{port}}/api/v1/fingering
Content-Type: application/json

{
  "type" : "piano",
  "chord" : "Cm"
}

### GET FINGERING
GET http://{{host}}:{{port}}/api/v1/fingering/1

### GET FINGERING LIST
GET http://{{host}}:{{port}}/api/v1/fingering?page=0&size=10

### PUT FINGERING
PUT http://{{host}}:{{port}}/api/v1/fingering/1
Content-Type: application/json

{
  "type" : "piano",
  "chord" : "2"
}

### DELETE FINGERING
DELETE http://{{host}}:{{port}}/api/v1/fingering/1