version: "3"

services:
  database:
    image: mysql
    container_name: sheetshow-sheet-mysql-container
    environment:
      - MYSQL_DATABASE=sheetshow-sheet
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=sheetshow-sheet
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/revision/docker_spring/database/sheetshow-sheet/:/var/lib/mysql
    networks:
      - basic_network

  redis:
    image: redis
    container_name: sheetshow-sheet-redis-container
    ports:
      - "6379:6379"
    networks:
      - basic_network


  application:
    image: "sheetshow-sheet"
    restart: always
    ports:
      - "8200:8200"
    depends_on:
      - database
    container_name: sheetshow-sheet-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/sheetshow-sheet?useSSL=false&serverTimezone=UTC&userlegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sheetshow-sheet
      SPRING_REDIS_HOST: redis
    networks:
      - basic_network
networks:
  basic_network: